version: '3'
services:
    web:
        container_name: fuel_web
        build:
            context: ./docker/nginx/
        volumes:
            - ./www:/var/www
        ports:
            - "9080:80"
        links:
            - app
    api:
        container_name: fuel_api
        build:
            context: ./docker/nginx/
        volumes:
            - ./www:/var/www
        ports:
            - "10443:10443"
        links:
            - app
        networks:
            - myfuel
    app:
        container_name: fuel_app
        build: 
            context: ./docker/php/
        volumes:
            - ./www:/var/www
            - ./mount/mysqld:/var/run/mysqld
        links:
            - mysql
            - redis
        networks:
            - myfuel
    mysql:
        container_name: fuel_mysql
        restart: always
        image: mysql:5.7 #latest
        volumes:
            - ./mount/db/mysql:/var/lib/mysql
            - ./mount/db/mysqld:/var/run/mysqld
#            - ./docker/mysql/seeders/initial.sql:/docker-entrypoint-initdb.d/initial.sql
        environment:
            - "MYSQL_DATABASE=myfuel"
            - "MYSQL_ROOT_PASSWORD=myfuel"
        ports:
            - "13306:3306"
        networks:
            - myfuel
    redis:
        container_name: fuel_redis
        restart: always
        image: redis:latest
        volumes:
            - ./redis:/data
        ports:
            - "16379:6379"
        command: redis-server --appendonly yes
        networks:
            - myfuel
networks:
    myfuel:
        driver: bridge

