version: '3'
services:
  memcached:
    image: memcached:1.4
    ports:
      - "11212:11211"

  data:
    image: busybox
    volumes:
      - ./mount/mysql_data:/var/lib/mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mysql_database
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_pw
    ports:
      - "13306:3306"
    volumes_from:
      - data
    volumes:
      - ./docker/mysql/seeders/initial.sql:/docker-entrypoint-initdb.d/initial.sql
    networks:
      - myfuel
    healthcheck:
      test: ["CMD", "${MYSQL_USER}", "ping", "-p${MYSQL_PASSWORD}"]
      retries: 3
      timeout: 5s

  nginx:
    build: ./docker/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/html
    links:
      - web
    networks:
      - myfuel

  web:
    # build: ./docker/php-fpm/5.6    # <- if you want to use PHP5.6
    build: ./docker/php-fpm/7.0
    # build: ./docker/php-fpm/7.1
    # build: ./docker/php-fpm/7.2
    # build: ./docker/php-fpm/7.3
    volumes:
      - ./:/var/www/html
    links:
      - mysql
    environment:
      DATABASE_HOST: 'mysql'
      DATABASE_NAME: 'mysql_database'
      DATABASE_USER: 'mysql_user'
      DATABASE_PASSWORD: 'mysql_pw'
    networks:
      - myfuel

networks:
    myfuel:
        driver: bridge

