version: '3'
services:
    web:
        container_name: web
        image: nginx:latest
        ports:
            - "8000:80" #local:8000 -> container:80
        depends_on:
            - app # appを先に起動
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./www:/var/www
    app:
        container_name: app
        build: 
            context: ./docker/php/
        volumes:
            - ./www:/var/www
        depends_on:
            - mysql # mysqlを先に起動
    mysql:
        container_name: mysql
        image: mysql:5.7
        volumes:
            - ./mount/db/mysql:/var/lib/mysql
            - ./mount/db/mysqld:/var/run/mysqld
            - ./docker/mysql/seeders/initial.sql:/docker-entrypoint-initdb.d/initial.sql
        environment:
            MYSQL_DATABASE: myfuel
            MYSQL_ROOT_PASSWORD: myfuel
            MYSQL_USER: myfuel
            MYSQL_PASSWORD: myfuel
        ports:
            - "3306:3306"
        restart: always
#    redis:
#        container_name: fuel_redis
#        restart: always
#        image: redis:latest
#        volumes:
#            - ./mount/redis:/data
#        ports:
#            - "16379:6379"
#        command: redis-server --appendonly yes

